### ISSUE TITLE
Spring Boot integration

### ISSUE THREAD

**Issue by mkopylec** [nielsbaloe/vertxui#11]
Any plans to implement integration with Spring Boot?

**Comment by nielsbaloe** [comment]
That is an interesting thought, thanks, no I do not have plans for it. Currently I see it as a very rich awesome proof-of-concept, which I myself use in some projects, but I also see that it is not being used widely. I guess mainly because writing a GUI completely reactive, is a bit too much. It requires some extra brainpower.

So for now, no spring boot integration, although this might actually be a good idea.
Thanks, Niels
