### ISSUE TITLE
Any online demo, example, showcase anywhere ?

### ISSUE THREAD

**Issue by remarkNS** [nielsbaloe/vertxui#2]
@nielsbaloe do you have any demo / example online anywhere to check how vertxui works / looks ? If not, any youtube movie to showcase something ?

**Comment by nielsbaloe** [comment]
Hmm no. But I can fix that. It won't be interesting though, the examples are small and they are visually then just a small showcase of whatever css-library is being used, you don't really see anything vertxui-specific (because there is no vertxui-specific GUI). Best is if you just load the projects into your eclipse and run the examples.
But I'll make some youtube movies, that's a usefull idea to me. Super thanks!

**Comment by nielsbaloe** [comment]
Hi,

I've created a video, see https://www.youtube.com/watch?v=ZusasYDjMKo . This is really from scratch, so I hope this suits a lot of needs.

Best,
Niels

**Comment by remarkNS** [comment]
Goed gedaan !
