### ISSUE TITLE
Components suite

### ISSUE THREAD

**Issue by Cafeinoman** [nielsbaloe/vertxui#3]
Hi,

it's not a real issue, but a question/improvement.
Do you plan to publish a components suite using your API?

**Comment by nielsbaloe** [comment]
Hi,

Thanks for your question, as far as I see it is is a very legitimate question.

Working on the examples, I realised that it is absolutely not necessary, because writing compoments with css libraries is the same as giving the appropriate css-class as argument. And, in vertxUI you are creating visual elements by always giving a css-class as argument. So it would not add anything.

However, for the sake of demonstration, I think I will add it anyway. As soon as I have more time for vertxUI, I will add examples for jQuery Mobile, PureCSS, and github.com/Dogfalo/materialize . By doing this I will introduce components, although these will basicly be one-liner classes.

Thanks!
Niels
